services:
  telegrampower:
    build: .
    restart: always
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    volumes:
      - power_data:/usr/src/app/mount


volumes:
  power_data: